apiVersion: v1
kind: Namespace
metadata:
  name: heptio-contour
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contour
  namespace: heptio-contour
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routes.contour.heptio.com
  labels:
    component: route
spec:
  group: contour.heptio.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: routes
    kind: Route
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          required:
            - host
            - routes
          properties:
            strategy:
              type: string
              enum:
                - RoundRobin
                - WeightedLeastRequest
                - Random
            lbHealthCheck:
              type: object
              required:
                - path
              properties:
                path:
                  type: string
                  pattern: ^\/.*
                intervalSeconds:
                  type: integer
                timeoutSeconds: 
                  type: integer
                unhealthyThresholdCount:
                  type: integer
                healthyThresholdCount:
                  type: integer
            host:
              type: string
            routes:
              type: array
              items:
                type: object
                required:
                  - pathPrefix
                  - upstreams
                properties:
                  pathPrefix:
                    type: string
                    pattern: ^\/.*
                  upstreams:
                    type: array
                    items:
                      required:
                        - serviceName
                        - servicePort
                      properties:
                        serviceName:
                          type: string
                        servicePort:
                          type: integer
                        weight:
                          type: integer
                        strategy:
                          type: string
                          enum:
                            - RoundRobin
                            - WeightedLeastRequest
                            - Random
                        lbHealthCheck:
                          type: object
                          required:
                            - path
                          properties:
                            path:
                              type: string
                              pattern: ^\/.*
                            intervalSeconds:
                              type: integer
                            timeoutSeconds: 
                              type: integer
                            unhealthyThresholdCount:
                              type: integer
                            healthyThresholdCount:
                              type: integer
