apiVersion: v1
kind: Service
metadata:
 name: contour
 namespace: heptio-contour
 annotations:
  # This annotation puts the AWS ELB into "HTTP" mode so that it adds the
  # `X-Forwarded-For` header on the request. If you aren't running on AWS this
  # should be a no-op.
  service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
 ports:
 - port: 80
   protocol: TCP
   targetPort: 8080
 selector:
   app: contour
 type: LoadBalancer
---
