language: go
go_import_path: github.com/heptio/contour
go:
  - 1.12.x

sudo: false

cache:
  directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

env:
  - GOPROXY=https://gocenter.io

install:
  - make download

script:
  - make check
