[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.2.1"

[[constraint]]
  name="k8s.io/client-go"
  version="~4.0"

[[override]]
  name="k8s.io/apimachinery"
  branch = "release-1.7"

[[override]]
  name="github.com/ugorji/go"
  revision="ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"

[[override]]
  name="github.com/gogo/protobuf"
  revision="c0656edd0d9eab7c66d1eb0c568f9039345796f7"

[[override]]
  name="github.com/golang/protobuf"
  revision="130e6b02ab059e7b717a096f397c5b60111cae74"
