apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- contour.heptio.com_ingressroutes.yaml
- contour.heptio.com_tlscertificatedelegations.yaml
- projectcontour.io_httpproxies.yaml
- projectcontour.io_tlscertificatedelegations.yaml
