name: Build and Test Pull Request

# Trigger the workflow on push or pull request
on: [push, pull_request]

env:
  GOPROXY: https://proxy.golang.org/
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: add deps to path
        run: |
          ./hack/actions/install-kubernetes-toolchain.sh $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - name: integration tests
        run: |
          make integration
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: test
        run: |
          go mod vendor
          make install
          make check-coverage
      - name: codeCoverage
        if: ${{ success() }}
        run: |
          CODECOV_NAME=coverage.out bash <(curl -s https://codecov.io/bash)
  test-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: test
        run: |
          go mod vendor
          make install
          make check-coverage
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          only-new-issues: true
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: generate
        run: |
          go mod vendor
          make generate
          ./hack/actions/check-uncommitted-codegen.sh
